apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myapp"
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myapp"
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/lufa199x/port-app
        
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: "myapp-lb"
  namespace: argocd

spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
